### ISSUE TITLE
Black screen after boot.

### ISSUE THREAD

**Issue by mosesbuckwalter** [rvmn/Lenovo-C930-bigsur-hackintosh#1]
Hello! I know this is a bit of an old project. I followed this guide on my Lenovo-C930 and it boots both Catalina and Big Sur seemingly fine, I here the macOS charging chime and macOS error sound when pressing keys, but the screen is all black. Do you have an idea why this might be? Thanks!

**Comment by rvmn** [comment]
Hi! Yeah it's a long time since I had it run and I cannot test anymore since i sold it. Did you unlock the cfg as written? And did you check it worked (with the checking function)? 
Otherwise, you might try connecting an external monitor and looking if that gives you a boot screen. It sounds a bit like the screen might be working but the screen's brightness is set to 0%, that should be easy to solve with an external monitor.

**Comment by mosesbuckwalter** [comment]
I did unlock the CFG, and I think I checked it, I unlocked it a few months ago but then put it on hold. I hooked it up to an external monitor and it’s all running. (Besides WiFi, I need to replace the card) If I change the brightness up and down, the backlight on the computer changes, but the screen remains black. Even the touch screen works, you just can’t see what you’re hitting. Seems like some sort of display driver issue?

**Comment by rvmn** [comment]
I did a quick search and it seems possibly a misconfigured graphics port, you could try using ioreg and following the steps to find the right graphics port, found [here](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html).
The wifi should be working using the heliport app, perhaps even works better by putting upgrading the itlwm kext (install [oc-configurator](https://mackie100projects.altervista.org/download-opencore-configurator/), load the efi folder (mount it using 'sudo mount -t msdos /boot/efi /dev/yourdrivenameandportnumber-like-nvme0n1p1-check-diskutil list'  and in the kexts tab, press update.). The itlwm installed is a heliport-version, you can might try downloading a new normal [itlwm.kext](https://github.com/OpenIntelWireless/itlwm) and putting it in the folder manually to not have to use heliport, here is some [info on the EFI folder setup, for background info](https://github.com/bil0u/hackintosh/blob/master/docs/config.md)

**Comment by mosesbuckwalter** [comment]
So I looked through all of this, still no luck, I've also tried changing the platform-id to other id's for the UHD 620, and that didn't work either. But macOS is running fine, (still can't figure the wifi even with newer kexts) and the screen works fine all through verbose and then its just black..... I'm stumped.

**Comment by rvmn** [comment]
Hmm, that is really awkward.. :( if you have also tried setting the GPU port right and that did not help one last option that perhaps helps is setting the 'UEFI boot only' option on in the BIOS, it might be that the card switches mode from legacy to uefi boot and then the GPU port changes, i heard about that somewhere. And as last option try choosing a different model instead, try macbook13,2 or higher or lower. Do keep backups of your config.plist in case it does not boot. I think i had the sepia screen problem back then and that was solved that way if i remember correctly.

**Comment by mosesbuckwalter** [comment]
So, in your EFI, conn1 is set to be a type of HDMI, I've tried changing it to DisplayPort, VGA, and LVDS, but none of that has worked. I also tried changing the model of MacBook, but didn't have luck with that either. What's interesting is there's 2 values for display0, one for the backlight, and one for the display. The backlight works perfectly, brightness is adjustable and everything, there's just no picture on it. :( 

As for the bios, I don't see any such option either :/

Thanks for the help!

Here is a screenshot of my IORegistry
![Screen Shot 2023-02-24 at 9 20 09 AM](https://user-images.githubusercontent.com/40410486/221202894-7ec95b60-dafc-420f-8446-e3ce1a356646.png)

**Comment by rvmn** [comment]
As a last 'wild guess' try this config, perhaps you have another revision with a different internal GPU port mapping although it looks the same in the ioreg: [config.plist.zip](https://github.com/rvmn/Lenovo-C930-bigsur-hackintosh/files/10828310/config.plist.zip)

**Comment by mosesbuckwalter** [comment]
Wow! It worked. The trackpad now doesn't work, but I'm guessing this config is just to test the display and isn't configured for anything else? Thank you so much, I can't believe it ha.

**Comment by mosesbuckwalter** [comment]
Also, now I have no usb-c display output...

**Comment by rvmn** [comment]
Yeah, that was just a quick edit, i didnt copy in usb-c mapping. try this one: 
[config.plist-new.zip](https://github.com/rvmn/Lenovo-C930-bigsur-hackintosh/files/10831194/config.plist-new.zip)

**Comment by mosesbuckwalter** [comment]
Still no usb-c display output, and with both of them I’m getting the 7mb VRAM error so I have no graphics acceleration. Adding in the device ID was supposed to fix that, but didn’t have any luck doing that.

**Comment by mosesbuckwalter** [comment]
Using the device-id 16590000 in combination with the platform-id 0000C087 I was able to get acceleration working and have the display recognized as a built-in-display instead of as a projector. Still no luck with USB-C display output. But everything else appears to be working! Thank you so much for your help with all of this, really appreciate it!!

**Comment by rvmn** [comment]
@mosesbuckwalter
Great to hear :+1: Theoretically you should have the following in your plist and usb-c should be active also:  
"framebuffer-con2-busid","Value":"06000000",
"framebuffer-con2-enable","Value":"01000000",
"framebuffer-con2-pipe","Value":"0A000000",
"framebuffer-con2-type","Value":"00040000"
Check that and see if that solves it or send me your plist if it doesnt, then i can take a look:)

**Comment by mosesbuckwalter** [comment]
Thanks, that didn't fix it, but here's my plist if you want to take a look I would really appreciate it. 

Another issue I'm having is it stays on while sleeping so it gets really warm and drains the battery, I'm not sure if you would know anything about that either.

Thank you again for all your help!! 
[config.plist.zip](https://github.com/rvmn/Lenovo-C930-bigsur-hackintosh/files/10893321/config.plist.zip)

**Comment by mosesbuckwalter** [comment]
Hey! I know it’s been awhile, thanks for all your help so far! I actually got the external display working, but am having issues when waking from sleep it often won’t wake up and will require a restart, did you experience this or know how I could fix this? Thanks

**Comment by rvmn** [comment]
@mosesbuckwalter 
i don´t know, can you see if the whole device is not turning on or just the screen? maybe if you have something like a usb fan or light or usb stick with a light you can see if it turns on usb ports.
then if it doesńt youŕe outa luck, you will need a dsdt patch for sleep that works better, maybe try search for a newer one. 
if it does and the screen doesnt you could try if you could theoretically use a cli script to run at logon that changes the resolution, which will in turn reset the gpu driver. something like this should work for that: https://github.com/davidmarkclements/screenres

**Comment by mosesbuckwalter** [comment]
Got it! The whole computer actually works, even with an external monitor, it is just the internal screen that breaks after sleep. I'll look into that script. Wouldn't it need to run every time after waking from sleep? Thanks!

**Comment by DarkIsTheNewLight** [comment]
Hey @mosesbuckwalter I was looking on doing this Hackintosh today. Do you still have your plist?

**Comment by mosesbuckwalter** [comment]
Hey there @DarkIsTheNewLight! I do, my hac’s battery was bad for a few months so I haven’t gotten around to fine tuning it. Right now every thing works flawlessly except for sleep. (I swapped the stock network card with an Apple supported one so I’m not using the Intel Wifi patch) If you figure out sleep that would be amazing… but I’ll upload my whole EFI folder for you to use or take a look at!

**Comment by mosesbuckwalter** [comment]
[config.plist.zip](https://github.com/rvmn/Lenovo-C930-bigsur-hackintosh/files/13494139/config.plist.zip)

Heres my config... the whole EFI is too big to upload in a comment but I can throw it on WeTransfer if you like.

**Comment by DarkIsTheNewLight** [comment]
Hey @mosesbuckwalter If you could throw in your EFI folder that would be great! This is my first hackintosh. Have you tried ventura or only big sur? Thanks so much!

**Comment by mosesbuckwalter** [comment]
I’m at work, but when I get home I’ll upload my EFI. I actually am on Catalina since I’m not a fan of the newer OS’s, but IIRC I did run Big Sur with no issues.
